apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-service-deployment
  labels:
    app: spring-boot-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-service
  template:
    metadata:
      labels:
        app: spring-boot-service
    spec:
      containers:
      - name: spring-boot-service
        image: somkiat/spring-boot-example
        ports:
        - containerPort: 8080
        env:
            - name: MONGO_URI
              value: mongo-service
